name: Build release image

on:
  push:
    tags:
      - '*'

jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Authenticate package registry
        run: echo "${{ secrets.CONTAINER_TOKEN }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: Get tag
        run: echo "BUILD_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build and tag image
        run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:${BUILD_TAG} -t ghcr.io/${GITHUB_REPOSITORY}:latest .

      - name: Push image
        if: success()
        run: docker push ghcr.io/${GITHUB_REPOSITORY}
